#=======================================================================
#
# Makefile
# --------
# Very simple makefile for the chacha test vectors generator.
#
#
# (c) 2013 Joachim Strombergson
#
#=======================================================================

(CC) = clang
(FLAGS) = -Wall -O2
(TARGET)=chacha
(SRC) = chacha.c

all:
	$(CC) $(FLAGS) -o chacha chacha.c

#=======================================================================
# EOF Makefile
#=======================================================================

